### ISSUE TITLE
Crashes in Irithyll

### ISSUE THREAD

**Issue by IvandeVain** [SirHalvard/Champions-Ashes#1]
Hi!
I've been using this mod since last thursday and have experienced some recurrent crashes on Irithyll. After getting tired of looking for the bonfires in Yorshka's Church and the entrance to the dungeons I decided to go open the shortcut to Pontiff and go for him. However whenever I get near the shortcut (at least from the pontiff's side) the game freezes and inmediatly crashes. I've repeated the experience for about 4 times, with the game always crashing. I also tried to open the other shortcut, the one in the area where the Pale Shadow invades you. The result is the same, the game crashes.

(BTW I'm also having some really weird lighting issues, but I don't know if those are a bug or a feature)

**Comment by Angeluso** [comment]
Thanks for the report. We'll try and fix this next patch.
What you can do for now are two things:
- Disable shadows in the advanced settings
- Revert back to vanilla lightning. This can be done by deleting drawparam in _ashes > param > drawparram and deleting everything but mapstudio in _ashes > map

**Comment by Angeluso** [comment]
Should be resolved now with 1.4.9.6
